import React, { useState } from "react";
import { Landmark, Scale, BookOpen, Search, ArrowRight, ShieldCheck, Printer } from "lucide-react";

export default function TorRules() {
  const [searchTerm, setSearchTerm] = useState("");

  const sections = [
    {
      id: "1",
      number: "1.",
      title: "TERMS OF REFERENCE (ToR)",
      subsections: [
        {
          num: "1.1",
          subtitle: "Program Background & Objectives",
          content: "Bridge to Growth is an institutional initiative managed by NCEI Lebanon to bridge the Lebanese startup ecosystem with the global diaspora. The program creates a data-driven Institutional Sandbox to facilitate secure, transparent, and high-impact cooperation, investment, and talent acquisition."
        },
        {
          num: "1.2",
          subtitle: "The Institutional Sandbox",
          content: "The Sandbox is a proprietary virtual environment managed by NCEI Lebanon. It functions as the primary platform for:",
          bullets: [
            "Centralized Documentation: Hosting verified business plans, feasibility studies, and due diligence materials.",
            "Milestone Tracking: Providing a real-time dashboard for investors and startups to monitor project progress and negotiation phases.",
            "Expert Oversight: Connecting participants with NCEI-appointed researchers and industry mentors to ensure alignment with international investment standards."
          ]
        }
      ]
    },
    {
      id: "2",
      number: "2.",
      title: "TERMS OF PARTICIPATION: STARTUPS & SEEKERS",
      subsections: [
        {
          num: "2.1",
          subtitle: "Eligibility & Vetting",
          content: "Requirements for startups to gain access to the NCEI virtual structures:",
          bullets: [
            "Verification: Startups must submit documentation proving legal entity status (or intent to incorporate) and provide a comprehensive Feasibility Study/Business Plan for NCEI review.",
            "Operational Readiness: Participants must demonstrate technical readiness and the ability to operate within the Sandbox environment.",
            "Commitment: By registering, startups commit to active engagement in the Sandbox for the duration of July 2026."
          ]
        },
        {
          num: "2.2",
          subtitle: "Obligations",
          bullets: [
            "Data Accuracy: All information shared within the Sandbox must be accurate, truthful, and updated regularly.",
            "Professionalism: Startups must adhere to NCEI's Code of Conduct, ensuring timely responses to investor inquiries and participating in scheduled 'Institutional Tank' sessions.",
            "Compliance: Participants must comply with all Lebanese regulatory frameworks and disclose any potential conflicts of interest during the matchmaking process."
          ]
        }
      ]
    },
    {
      id: "3",
      number: "3.",
      title: "TERMS OF PARTICIPATION: INVESTORS",
      subsections: [
        {
          num: "3.1",
          subtitle: "Eligibility & Vetting",
          content: "Vetting standards mapped to diaspora trusts and institutional partners:",
          bullets: [
            "Investor Profile: Open to Angel Investors, Venture Capitalists, Diaspora Business Leaders, and representatives from NGOs/International Organizations.",
            "Disclosure: Investors are encouraged to provide a brief 'Investment Mandate' (sectors of interest, ticket size, and risk appetite) to improve the efficacy of the automated matching engine."
          ]
        },
        {
          num: "3.2",
          subtitle: "Obligations",
          bullets: [
            "Code of Conduct: Investors agree to act with transparency and integrity, providing constructive feedback to startups even when declining a proposal.",
            "Confidentiality: All proprietary business plans and sensitive data accessed within the Sandbox are subject to a Strict Non-Disclosure Agreement (NDA). Proprietary information shall not be disseminated outside the NCEI Sandbox environment.",
            "Due Diligence Respect: While NCEI performs preliminary vetting, investors acknowledge that they remain responsible for their own final due diligence and investment decisions."
          ]
        }
      ]
    },
    {
      id: "4",
      number: "4.",
      title: "INTELLECTUAL PROPERTY & DATA PRIVACY",
      subsections: [
        {
          num: "4.1",
          subtitle: "IP Protection",
          content: "NCEI Lebanon does not claim ownership of any Intellectual Property generated by participants. All innovations remain the property of the respective startup/founder."
        },
        {
          num: "4.2",
          subtitle: "Data Protection",
          content: "NCEI Lebanon operates under strict data privacy protocols. No personal or proprietary information will be shared with third parties outside the program without the express written consent of the owner."
        },
        {
          num: "4.3",
          subtitle: "Sandbox Security",
          content: "All interactions within the Sandbox are logged for transparency and accountability, providing an audit trail for future investment rounds."
        }
      ]
    },
    {
      id: "5",
      number: "5.",
      title: "OPERATIONAL GOVERNANCE",
      subsections: [
        {
          num: "5.1",
          subtitle: "NCEI Mediation",
          content: "NCEI Lebanon acts as the primary intermediary. In the event of a dispute or communication breakdown between parties, NCEI reserves the right to intervene to facilitate a resolution."
        },
        {
          num: "5.2",
          subtitle: "Exit Clause",
          content: "NCEI reserves the right to suspend or remove any participant (startup or investor) found in breach of the Code of Conduct or the Terms of Participation."
        },
        {
          num: "5.3",
          subtitle: "Reporting",
          content: "NCEI Lebanon will generate summary reports on the ecosystem's performance post-July, utilizing aggregated, anonymized data to advocate for policy improvements with the public sector."
        }
      ]
    }
  ];

  const filteredSections = sections.filter((sec) => {
    const sectionMatch = sec.title.toLowerCase().includes(searchTerm.toLowerCase());
    const subsecMatch = sec.subsections.some((sub) => 
      sub.subtitle?.toLowerCase().includes(searchTerm.toLowerCase()) || 
      sub.content?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (sub.bullets && sub.bullets.some((b) => b.toLowerCase().includes(searchTerm.toLowerCase())))
    );
    return sectionMatch || subsecMatch;
  });

  return (
    <div className="max-w-5xl mx-auto space-y-8 text-black" id="tor_rules_root">
      
      {/* Editorial Header Block */}
      <div className="border-4 border-black bg-zinc-900 text-white p-6 md:p-8 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2 font-mono text-xs text-zinc-300 font-extrabold uppercase">
            <Landmark className="w-4 h-4 text-emerald-400" />
            <span>Go-to-Market Guidance Protocol | July 2026</span>
          </div>
          <h2 className="font-syne font-black text-2xl md:text-3.5xl uppercase tracking-tighter leading-none">
            Terms of Reference & Participation
          </h2>
          <p className="text-xs text-zinc-400 font-mono leading-relaxed max-w-xl">
            Governing framework for all interactions between NCEI Lebanon, participating startups, and diaspora investors.
          </p>
        </div>
        <button
          onClick={() => window.print()}
          className="bg-white text-black hover:bg-zinc-100 border-2 border-black font-mono text-xs font-bold px-4 py-2 shrink-0 flex items-center gap-2 cursor-pointer transition-all active:translate-y-0.5"
          title="Print official guidelines"
        >
          <Printer className="w-4 h-4" />
          <span>Print ToR</span>
        </button>
      </div>

      {/* Internal Fast-Search Filter */}
      <div className="flex items-center gap-3 bg-zinc-100 border-4 border-black p-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
        <Search className="w-5 h-5 text-black shrink-0" />
        <input
          type="text"
          placeholder="SEARCH LEGISLATIVE PHRASES (e.g. Vetting, IP, Sandbox)..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full text-xs font-mono font-bold bg-transparent outline-none uppercase placeholder-gray-500"
        />
        {searchTerm && (
          <button 
            onClick={() => setSearchTerm("")} 
            className="text-xs font-mono font-extrabold underline text-black hover:text-zinc-600"
          >
            CLEAR
          </button>
        )}
      </div>

      {/* Two Columns: Sidebar links & Core document content */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Sidebar Nav */}
        <div className="lg:col-span-4 space-y-4 lg:sticky lg:top-24">
          <div className="border-4 border-black bg-white p-5 space-y-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <h4 className="font-syne font-black text-xs uppercase tracking-wider text-black border-b border-black pb-2 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-black" />
              <span>Section Directory</span>
            </h4>
            <div className="space-y-1 text-xs font-mono font-bold uppercase">
              {sections.map((sec) => (
                <a
                  key={sec.id}
                  href={`#sec-${sec.id}`}
                  className="block p-2 hover:bg-zinc-100 border border-transparent hover:border-black text-black group flex items-center justify-between"
                >
                  <span className="truncate">{sec.title}</span>
                  <ArrowRight className="w-3.5 h-3.5 text-black opacity-0 group-hover:opacity-100 transition-opacity" />
                </a>
              ))}
            </div>
          </div>

          <div className="border-4 border-black bg-[#E6F3FF] p-5 space-y-3 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <h4 className="font-mono text-xs font-black text-black uppercase tracking-wider flex items-center gap-1.5">
              <Scale className="w-4 h-4" />
              <span>Jurisdiction</span>
            </h4>
            <p className="text-[11px] text-gray-700 leading-relaxed font-sans font-medium">
              NCEI Lebanon acts as the transparent mediator, ensuring legal templates conform to standard global sandbox structures while respecting sovereign municipal rules.
            </p>
          </div>
        </div>

        {/* Corporate Doc Content */}
        <div className="lg:col-span-8 bg-white border-4 border-black p-6 md:p-8 space-y-8 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]" id="tor_print_zone">
          {filteredSections.map((sec) => (
            <div key={sec.id} id={`sec-${sec.id}`} className="space-y-4 border-b-2 border-dashed border-zinc-200 pb-6 last:border-none">
              <div className="flex items-baseline gap-2">
                <span className="font-syne font-black text-xl text-black">{sec.number}</span>
                <h3 className="font-syne font-black text-xl text-black uppercase tracking-tight">
                  {sec.title}
                </h3>
              </div>

              <div className="space-y-4 pl-4 border-l-2 border-black">
                {sec.subsections.map((sub, sIdx) => (
                  <div key={sIdx} className="space-y-2">
                    {sub.subtitle && (
                      <h4 className="font-mono text-xs font-black text-zinc-900 uppercase">
                        {sub.num ? sub.num + " " : ""}{sub.subtitle}
                      </h4>
                    )}
                    {sub.content && (
                      <p className="text-xs text-gray-700 font-sans font-medium leading-relaxed normal-case">
                        {sub.content}
                      </p>
                    )}
                    {sub.bullets && (
                      <ul className="space-y-2 text-xs font-sans font-medium text-gray-700 pl-4 list-disc">
                        {sub.bullets.map((b, bIdx) => (
                          <li key={bIdx} className="leading-relaxed">
                            {b}
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}

          {filteredSections.length === 0 && (
            <div className="p-8 text-center text-xs font-mono font-bold text-gray-500 bg-zinc-50 border border-zinc-200">
              NO COMPLIANCE SECTIONS COMPORTED TO "{searchTerm.toUpperCase()}"
            </div>
          )}

          {/* Golden Affirmation Lock */}
          <div className="bg-zinc-900 text-white p-6 border-4 border-black relative overflow-hidden transition-all uppercase select-none">
            <div className="absolute top-0 right-0 p-8 opacity-5">
              <Scale className="w-32 h-32 text-white" />
            </div>
            <div className="relative z-10 space-y-4">
              <div className="flex items-center gap-2 font-mono text-xs text-emerald-400 font-black">
                <ShieldCheck className="w-5 h-5 text-emerald-400" />
                <span>AGREEMENT AFFIRMATION</span>
              </div>
              <p className="text-[11px] text-zinc-300 font-mono leading-relaxed normal-case text-justify">
                By registering on the NCEI platform, all parties acknowledge they have read, understood, and agreed to these Terms of Participation. Failure to comply with these terms may result in immediate expulsion from the Sandbox and forfeiture of access to NCEI institutional backing.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
